GET http://localhost:8000/students

###
GET http://localhost:8000/students/63ca1f7965547b948f34ce64

###
POST http://localhost:8000/students
Content-Type: application/json

{
    "name": "Dayshawn",
    "class": "Software Engineer"
}

###
PATCH http://localhost:8000/students/63c9d48879b6e32c9c6135ad
Content-Type: application/json

{
    "name": "Time NEW",
    "class": "Industrial NEW"
}



###
DELETE http://localhost:8000/students/63c5c3bd57826814a1e152d6
